spring.application.name=DMS
spring.datasource.url=jdbc:sqlserver://DESKTOP-VSQSLHO:1433;databaseName=DMS;encrypt=false;trustServerCertificate=true;instanceName=MSSQLSERVER2
spring.datasource.username=Atos
spring.datasource.password=Atos
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.javax.persistence.validation.mode=none

#spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=update
